//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentMethods {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
#if NetCore
                    var assembly = typeof(Strings).GetTypeInfo().Assembly;
#else
                    var assembly = typeof(Strings).Assembly;
#endif
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentMethods.Strings", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple custom attributes of the same type found: {0}..
        /// </summary>
        internal static string AmbiguousAttributes {
            get {
                return ResourceManager.GetString("AmbiguousAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index is out of bounds for the array or length is greater than the number of elements from index to the end of the source array..
        /// </summary>
        internal static string ArgumentOutOfRange_ArraySlice {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ArraySlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive number required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedPosNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedPosNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot box the non-value type {0}..
        /// </summary>
        internal static string CannotBox {
            get {
                return ResourceManager.GetString("CannotBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast the value type {0}..
        /// </summary>
        internal static string CannotCast {
            get {
                return ResourceManager.GetString("CannotCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of field &apos;{0}&apos; is null, and cannot be converted to {1}..
        /// </summary>
        internal static string CannotCastNullToValueType {
            get {
                return ResourceManager.GetString("CannotCastNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to the value type {0}..
        /// </summary>
        internal static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to the type {0} with overflow check..
        /// </summary>
        internal static string CannotConvertChecked {
            get {
                return ResourceManager.GetString("CannotConvertChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to the type {0} with unsigned overflow check..
        /// </summary>
        internal static string CannotConvertCheckedUnsigned {
            get {
                return ResourceManager.GetString("CannotConvertCheckedUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null or empty string to type {0}..
        /// </summary>
        internal static string CannotConvertNullToValueType {
            get {
                return ResourceManager.GetString("CannotConvertNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from {0} to type {1} of property {2} for component {3}..
        /// </summary>
        internal static string CannotConvertPropertyValue {
            get {
                return ResourceManager.GetString("CannotConvertPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from {0} to type {1}..
        /// </summary>
        internal static string CannotConvertValue {
            get {
                return ResourceManager.GetString("CannotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property &apos;{0}&apos; cannot be found in the type {1}..
        /// </summary>
        internal static string CannotFindTypeMember {
            get {
                return ResourceManager.GetString("CannotFindTypeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize the non-value type {0}..
        /// </summary>
        internal static string CannotInitialize {
            get {
                return ResourceManager.GetString("CannotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        internal static string CannotNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from the property `{0}` on the type {1}..
        /// </summary>
        internal static string CannotReadProperty {
            get {
                return ResourceManager.GetString("CannotReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store a {0} value in a local of type {1}..
        /// </summary>
        internal static string CannotStoreLocal {
            get {
                return ResourceManager.GetString("CannotStoreLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unbox the non-value type {0}..
        /// </summary>
        internal static string CannotUnbox {
            get {
                return ResourceManager.GetString("CannotUnbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unbox.any the non-value type {0}..
        /// </summary>
        internal static string CannotUnboxAny {
            get {
                return ResourceManager.GetString("CannotUnboxAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the field `{0}` on the type {1}..
        /// </summary>
        internal static string CannotWriteField {
            get {
                return ResourceManager.GetString("CannotWriteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the property `{0}` on the type {1}..
        /// </summary>
        internal static string CannotWriteProperty {
            get {
                return ResourceManager.GetString("CannotWriteProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not belong to the record..
        /// </summary>
        internal static string FieldCannotBeFound {
            get {
                return ResourceManager.GetString("FieldCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field `{0}` on the type {1} is not of type {2}..
        /// </summary>
        internal static string FieldTypeNotMatch {
            get {
                return ResourceManager.GetString("FieldTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order syntax is invalid: {0}..
        /// </summary>
        internal static string InvalidOrderSyntax {
            get {
                return ResourceManager.GetString("InvalidOrderSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one matching element.
        /// </summary>
        internal static string MoreThanOneMatch {
            get {
                return ResourceManager.GetString("MoreThanOneMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non negative number is required..
        /// </summary>
        internal static string NeedNonNegNum {
            get {
                return ResourceManager.GetString("NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no elements.
        /// </summary>
        internal static string NoElements {
            get {
                return ResourceManager.GetString("NoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no event named with `{0}` on the type {1}..
        /// </summary>
        internal static string NoEvent {
            get {
                return ResourceManager.GetString("NoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type {0} does not have a public constructor taking only a string parameter..
        /// </summary>
        internal static string NoExceptionConstructor {
            get {
                return ResourceManager.GetString("NoExceptionConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no field named with `{0}` on the type {1}..
        /// </summary>
        internal static string NoField {
            get {
                return ResourceManager.GetString("NoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no matching element.
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no property named with `{0}` on the type {1}..
        /// </summary>
        internal static string NoProperty {
            get {
                return ResourceManager.GetString("NoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not represent a field..
        /// </summary>
        internal static string NotFieldExpression {
            get {
                return ResourceManager.GetString("NotFieldExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not represent a method call..
        /// </summary>
        internal static string NotMethodExpression {
            get {
                return ResourceManager.GetString("NotMethodExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not represent a property..
        /// </summary>
        internal static string NotPropertyExpression {
            get {
                return ResourceManager.GetString("NotPropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed Stream..
        /// </summary>
        internal static string ObjectDisposed_StreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property `{0}` on the type {1} is not of type {2}..
        /// </summary>
        internal static string PropertyTypeNotMatch {
            get {
                return ResourceManager.GetString("PropertyTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single dimension arrays are supported here..
        /// </summary>
        internal static string Rank_MultiDimNotSupported {
            get {
                return ResourceManager.GetString("Rank_MultiDimNotSupported", resourceCulture);
            }
        }
    }
}
